#!/usr/bin/env node
const fa = require('../site/data/farm_actors.json');
const AUTONAME_OWNER = /^[a-z]+[0-9]{2,}[a-z]*$/;
const entries = Object.keys(fa);
const realish = entries.filter(a => !AUTONAME_OWNER.test(a));
// org-suspicious: realish names with many hours that aren't farm-looking
const ORGS = ['conda-forge', 'posthog', 'microsoft', 'getsentry', 'n8n-io', 'openclaw', 'tenstorrent', 'elastic', 'pytorch', 'pytorch', 'vercel', 'google', 'aws', 'facebook', 'meta', 'apple', 'amazon', 'github', 'docker', 'kubernetes', 'grafana', 'hashicorp', 'mongodb', 'stripe', 'shopify', 'netflix', 'spotify', 'cloudflare', 'jetbrains', 'gitlab', 'atlassian', 'datadog', 'twilio', 'slack', 'discord', 'notion', 'figma', 'canva', 'dropbox', 'sentry', 'netlify', 'supabase', 'firebase', 'openai', 'anthropic', 'huggingface', 'rust-lang', 'nodejs', 'golang', 'mozilla', 'torvalds', 'npm', 'denoland', 'vitejs', 'sveltejs', 'vuejs', 'angular', 'reactjs', 'linux', 'homebrew', 'nixos', 'debian', 'ubuntu', 'fedora', 'archlinux', 'gentoo', 'kde', 'gnome', 'apache', 'eclipse', 'mozilla', 'wikimedia', 'torproject', 'signalapp', 'telegram', 'whatsapp', 'instagram', 'linkedin', 'tiktok', 'snapchat', 'reddit', 'pinterest', 'ebay', 'paypal', 'square', 'robinhood', 'coinbase', 'blockchain', 'ethereum', 'bitcoin', 'solana', 'cardano', 'polkadot', 'cosmos', 'chainlink', 'uniswap', 'pancakeswap', 'sushiswap', 'aave', 'compound', 'makerdao', 'curve', 'balancer', 'synthetix', 'yearn', 'harvest', 'badger', 'alpha', 'cream', 'bancor', '1inch', '0x', 'matic', 'avalanche', 'near', 'algorand', 'tezos', 'eos', 'tron', 'ada', 'dot', 'atom', 'xrp', 'stellar', 'ripple', 'litecoin', 'dogecoin', 'monero', 'zcash', 'dash', 'bitcoincash', 'ethereumclassic', 'binance', 'coinbase', 'kraken', 'gemini', 'bitfinex', 'bitstamp', 'okx', 'bybit', 'kucoin', 'huobi', 'gate', 'mexc', 'bitget', 'woo', 'crypto', 'binance-smart-chain', 'polygon', 'avalanche', 'fantom', 'arbitrum', 'optimism', 'zksync', 'starknet', 'loopring', 'immutable', 'godsunchained', 'sandbox', 'decentraland', 'axie', 'smooth', 'steps', 'metamask', 'walletconnect', 'rainbow', 'trustwallet', 'exodus', 'ledger', 'trezor', 'keepkey', 'coolwallet', 'safepal', 'onekey', 'imtoken', 'mathwallet', 'tokenpocket', 'bitkeep', 'zerion', 'zapper', 'zksync'];
const poisoned = realish.filter(a => ORGS.includes(a));
console.log('KNOWN ORGS in ledger:', poisoned.length, poisoned.map(a => a + '(' + fa[a].hours.length + 'h)').join(', '));
// top realish with >=10 hours — the confirmed long-running ones
console.log('\ntop realish >=10h:');
realish.filter(a => fa[a].hours.length >= 10).sort((a, b) => fa[b].hours.length - fa[a].hours.length)
  .forEach(a => console.log(' ', a.padEnd(28), fa[a].hours.length + 'h', 'last:' + fa[a].lastSeen));
