#!/usr/bin/env node
// Debug: reprocess hour 8-9 with the CURRENT code and log which repos seed the
// ledger with owner 'posthog' — but without writing files.
const fs = require('fs');
const path = require('path');

// minimal harness: reuse pipeline functions by requiring the module? pulse.cjs
// runs main() on require — so instead, simulate the flag logic here.
const AUTONAME_OWNER = /^[a-z]+[0-9]{2,}[a-z]*$/;
const AUTONAME_REPO = /^[a-z]{4,8}$/;
const SHARED_BOTS = new Set(['github-actions[bot]', 'dependabot[bot]', 'renovate[bot]']);
function isAutoGeneratedName(repo) {
  const [owner = '', rname = ''] = String(repo || '').toLowerCase().split('/');
  return AUTONAME_OWNER.test(owner) && AUTONAME_REPO.test(rname);
}
// load hour 8 snapshot
const h8 = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'site', 'data', 'history', '2026-08-11-8.json')));
// find posthog-owned repos in ALL stored lists of hour 8
const lists = { top_hot: h8.top_hot, top_active: h8.top_active, top_human: h8.top_human, bot_watch: h8.bot_watch, demoted: h8.demoted };
for (const [ln, list] of Object.entries(lists)) {
  for (const r of list || []) {
    if (String(r.repo || '').toLowerCase().startsWith('posthog')) {
      console.log('hour8', ln, r.repo, 'flag:', r.flag, 'pushes:', r.pushes, 'actors:', r.actors, 'prs:', r.prs, 'issues:', r.issues, 'stars:', r.stars, 'actor_names:', (r.actor_names || []).join(','));
    }
  }
}
// also scan hours 0-7
for (let hnum = 0; hnum <= 7; hnum++) {
  const f = `2026-08-11-${hnum}.json`;
  const p = path.join(__dirname, '..', 'site', 'data', 'history', f);
  if (!fs.existsSync(p)) continue;
  const h = JSON.parse(fs.readFileSync(p));
  for (const [ln, list] of Object.entries({ top_hot: h.top_hot, top_active: h.top_active, top_human: h.top_human, bot_watch: h.bot_watch, demoted: h.demoted })) {
    for (const r of list || []) {
      if (String(r.repo || '').toLowerCase().startsWith('posthog')) {
        console.log(f, ln, r.repo, 'flag:', r.flag, 'pushes:', r.pushes, 'actors:', r.actors);
      }
    }
  }
}
