// update_report_v530.cjs — insert v5.25/v5.26 timeline entries, add v5.30 entry, update panel-sub + verdict
const fs = require('fs');
const p = 'pipeline/report.cjs';
let t = fs.readFileSync(p, 'utf8');
const chk = (ok, what) => { if (!ok) throw new Error('FAILED: ' + what); console.log('OK:', what); };

// ---- 1) insert v5.25 + v5.26 before the v5.27 timeline line (timeline uses PLAIN quotes) ----
const anchor1 = 'Aug 16 · hours 13–15';
const i1 = t.indexOf(anchor1);
chk(i1 > 0, 'anchor1 (v5.27 line)');
const lineStart = t.lastIndexOf('\n  { when: "', i1) + 1;
chk(lineStart > 0, 'line start before v5.27');
const ins1 = String.raw`  { when: "Aug 16 · hours 7–9", title: "The biggest magazine ever fires — 5th live test passed (v5.25)", body: "The factory did NOT peak at h6 — it saved the biggest for h7. Minting 968 (h5) → 1,553 (h6) → 1,630 (h7, biggest single hour since the 2,002 record) → 867 (h8) → 608 (h9) = 5,626 fresh accounts in 5 hours; the h5–h7 triple (4,151) is the all-time 3-hour mint record. The wave it bought: h7 34.4% (−18.3pt, the deepest dip of the siege — the batch sat parked), h8 46.5%, h9 64.1% RE-BREACH (hair under the top-10 highest hours). Mint → dip → breach in 2–4h: the 5th consecutive lead-time live test passed. ugmoddev's decay is structural (95 → 74/hr, still 130 of 130 hours); elad-cmd off 4h+; Janfindl confirmed shift worker (3-on/1-off); zerotraceh1 NOT retired (returned 68/60/hr — weakest ever); ThatOneFrench's crown RETRACTED (4-hour shift, gone). NEW naming mutation: hyphen+digits (miller-e6513). Demotions: h9's 3,585 = ALL-TIME RECORD. Ledger 29,149; 130h gapless · 21.22M events; report v5.25 GREEN, deployed HTTP 200, SMOKE PASS, shot run39. HN: 49310247 alive ~21h (delayed-kill watch passed x3)." },
  { when: "Aug 16 · hours 10–12", title: "THE NOON RITUAL — a farm that punches the clock (v5.26)", body: "loganfoxdale/d3 pushed at EXACTLY hour 12 for SIX consecutive days (312/351/183/227/119/109/hr), same actor, same repo, cron-regular — found via full-trace replay because it is invisible in per-hour bot_watch. The 6th lead-time live test PASSED: h10 62.7% → h11 51.7% → h12 55.4% — four straight ≥50% hours (h9–h12), wave PEAK. ugmoddev OUT of the top-15 farms for the FIRST time in 133h (70/hr vs the 71 cutoff — still the 4th most-active actor overall; my earlier 'silent' read corrected). elad-cmd returned at h10 (75/hr) then off again; Janfindl's 3-on/1-off broke (off h9–h12 — the morning-shift pattern); zerotraceh1's fade confirmed (weakest-ever 68/60 then gone); the hyphen+digit squad = solo on/off shifts, NOT one-hits (83/0/64/0). NEW DISGUISE TIER: real-word usernames (forgetpwd, twainswee, spl1ce, janbeoty). DEMOTION RECORD SPREE: h9 3,585 record + h10 3,225 (2nd-biggest EVER) + h11 2,900 (6th) — three of the top-6 all-time demotion hours in one window. Factory magazine spent (5,626 h5–h9), re-arming 214/449/440. 133h gapless · 21.73M events; ledger 29,065; report v5.26 GREEN, deployed HTTP 200, SMOKE PASS, shot run40. HN: delayed-kill MEASURED — 49319786 created 13:14Z, #1 on /newest, dead within ~5 min; 49310247 still alive 24h+; Ask 49270205 alive 4 days; URL budget exhausted (survival was luck, not an unlock)." },
`;
t = t.slice(0, lineStart) + ins1 + t.slice(lineStart);

// ---- 2) insert v5.30 timeline entry before the `];` that closes the timeline array ----
const anchor2 = '23.74M events.';
const i2 = t.indexOf(anchor2);
chk(i2 > 0, 'anchor2 (v5.29 timeline body)');
const closeIdx = t.indexOf('\n];', i2);
chk(closeIdx > 0, 'timeline array close');
const ins2 = String.raw`  { when: "Aug 17 · hours 1–3", title: "THE 18-HOUR SIEGE BREAKS — and the factory answers with its biggest magazine in 44 hours (v5.30)", body: "The record run did not just end — it doubled the old record first. h1 58.5% → h2 62.8% extended the siege to EIGHTEEN consecutive ≥50% hours (h9 Aug 16 → h2 Aug 17; the pre-siege all-time record was 10), then h3 collapsed to 42.2% (−20.6pt, the first sub-50% hour in 18). Post-peak-collapse was falsified five times during the run, but the collapse finally came — on schedule with the factory: 75 → 299 → 1,338 fresh accounts minted h1→h3, the 4th-biggest single-hour mint ever (behind 1,630/1,553/1,497) and the first ≥1,000 magazine since Aug 16 h7 — mint-at-collapse is now the factory's signature (2,002 at h12 Aug 14, 1,497 at h6 Aug 15, 1,180 at h14 Aug 15, 1,338 at h3). The lead-time rule's next live test: breach expected h4–h6 (next run). zerotraceh1 RETURNED (19/24/12 pushes h1–h3 — first activity since Aug 16 h9), the cycler re-entering exactly as the streak died; elad-cmd ran a clean 3-hour shift (164/157/88, psycho-usage #2 at h2); ugmoddev active all window (266/251/141; noti-api-server 158 at h2) — no zombie gap this time. srjordan6/twoai-content worked its second straight night (212/183) — a night-shift worker, not a one-hit. New real-word one-hits: flintassemblyduel (320 h1), Fueltricharge (316/210 h1–h2), SkinCorporal (169 h2), SailorEnliven (145 h3), contrerasjake7319 (200/132 h2–h3); animal-lover12 = new persistent veteran (8 of 9h, 89–169/hr). CORRECTIONS via archive-level tracing: (1) bogdanstancu1119-maker — #1 non-bot actor at 710/634/353 events/hr — is a PUSH-SPRAY farm, not commit-based: 100% PushEvents across 13 repos at ~27–55/repo/hr, every repo under the top-15 cutoff (invisible in bot_watch/demoted, but ledger-tracked 62h and its repos ARE demoted from heat). (2) 'h12-only' was a visibility artifact: 41 of 46 noon-cohort actors are genuinely h12-only across six scanned night hours, but loganfoxdale drips 18–60/hr at h1–h3 nightly (two days verified) and reinatomait/yonghuy/nuanton ALL fired at exactly Aug 17 h2 on fresh 6-char repos — the scheduler runs an h2 shift too. (3) ledger hours for veterans are dense first→last intervals (148/148 = interval coverage, not per-hour activity). Ledger 26,413 (23,414 confirmed) — third consecutive decline (pruning still outruns the mint). Demotions cooled: 1,821/2,310/2,006. HN: 49310247 alive 39h+ (all-time URL-post record), karma 3 → no posts (discipline). 77 of 148 hours ≥50% · 24.25M events." },
`;
t = t.slice(0, closeIdx + 1) + ins2 + t.slice(closeIdx + 1);

// ---- 3) panel-sub (v5.29 -> v5.30); the old span has no double quotes ----
const oldSub = 'v5.29 — RECORD SHATTERED: 16 straight ≥50% hours (h9→h0, old record 10), wave still PEAK (64.9%) on a dead factory (92/hr mint, h19 lowest ever at 26); NOON RITUAL = SHARED SCHEDULER: 46 h12-only actors across 6 days; ugmoddev zombie bursts but 145/145 ledger hours; ledger 26,761 (−528, 2nd decline)';
const newSub = 'v5.30 — THE 18-HOUR SIEGE BREAKS (h3 42.2%, −20.6pt; record run h9→h2 = 18, old record 10) and the factory answers with 1,338 minted AT the dip (4th-biggest ever); zerotraceh1 returns; bogdanstancu decoded as push-spray farm; ledger 26,413 (3rd decline)';
chk(t.includes(oldSub), 'panel-sub old text');
t = t.replace(oldSub, newSub);

// ---- 4) verdict (v5.29 -> v5.30); region contains no double quotes ----
const vStart = t.indexOf('VERDICT (v5.29):');
chk(vStart > 0, 'verdict start');
const endMarker = '23.74M events.</b></div>';
const vEnd = t.indexOf(endMarker, vStart);
chk(vEnd > 0, 'verdict end marker');
const newVerdict = String.raw`VERDICT (v5.30): THE 18-HOUR SIEGE FINALLY BREAKS — AND THE FACTORY ANSWERS WITH ITS BIGGEST MAGAZINE IN 44 HOURS. h1 58.5% → h2 62.8% pushed the record run to <b>EIGHTEEN consecutive ≥50% hours (h9 Aug 16 → h2 Aug 17)</b> — the old all-time record was 10 — then h3 collapsed to 42.2% (−20.6pt): the longest breach run ever measured is dead. The collapse came with the factory re-arming AT the dip: 75 → 299 → <b>1,338 fresh accounts minted h1→h3</b> — the 4th-biggest single-hour mint ever (behind only 1,630/1,553/1,497) and the first ≥1,000 magazine since Aug 16 h7 — so the lead-time rule's next live test is armed for h4–h6 (next run). The 18-hour siege itself ran on ~92/hr minting — the standing army IS the wave — but the factory still answers every collapse. <b>zerotraceh1 RETURNED</b> — silent since Aug 16 h9, it pushed 19/24/12 at h1–h3, the cycler coming back exactly as the streak died. elad-cmd ran a clean 3-hour shift (164/157/88, psycho-usage #2 at h2); ugmoddev stayed active all window (266/251/141, noti-api-server 158 at h2) — no zombie gap this time. srjordan6/twoai-content: second straight night (212/183) — a night-shift worker, not a one-hit. New real-word one-hits (flintassemblyduel 320, Fueltricharge 316/210, SkinCorporal 169, SailorEnliven 145, contrerasjake7319 200/132); animal-lover12 = new persistent veteran (8 of 9h, 89–169/hr). <b>CORRECTIONS via archive-level tracing:</b> (1) bogdanstancu1119-maker (710/634/353 — the #1 non-bot actor on GitHub) is NOT a commit-based farm: GH Archive proves 100% PushEvents — it is a <b>push-SPRAY farm</b>, 13 repos at ~27–55 pushes/repo/hr, every repo under the top-15 cutoff, so it never surfaces in bot_watch or demoted (but it IS in the ledger, 62h, and its repos ARE demoted from heat). (2) 'h12-only' was a top-list artifact: archive-level scans of six night hours show 41 of 46 noon-cohort actors are genuinely h12-only, but loganfoxdale drips 18–60/hr at h1–h3 nightly (two days verified) and reinatomait/yonghuy/nuanton ALL pushed at exactly Aug 17 h2 on fresh repos — the scheduler runs an h2 shift too; every earlier 'zero elsewhere' trace missed sub-cutoff activity. (3) ledger hours for veterans are dense first→last intervals — 148/148 is interval coverage, not per-hour activity. Demotions cooled to 1,821/2,310/2,006 — no new all-time entries. Ledger 26,413 (23,414 confirmed) — <b>third consecutive decline</b>. HN: 49310247 alive 39h+ (all-time URL-post record), karma 3 → no posts. 77 of 148 hours ≥50% · 24.25M events.</b></div>`;
t = t.slice(0, vStart) + newVerdict + t.slice(vEnd + endMarker.length);

fs.writeFileSync(p, t);
console.log('DONE, all 4 edits applied');
